"""Strategy nursery — shadow/probation testing for new parameter sets.

New or mutated parameter sets run in shadow mode (no real trades)
for a minimum of 30 trades. They generate signals alongside active
models, and their predictions are evaluated against actual outcomes.

If the shadow parameters outperform the current active set → promote.
If they underperform → discard.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone

import structlog

from config.constants import LEARNING_SAFETY_RAILS

logger = structlog.get_logger(__name__)

MIN_SHADOW_TRADES = LEARNING_SAFETY_RAILS["min_shadow_trades_for_promotion"]  # 30


@dataclass
class ShadowSignal:
    """A signal generated by a shadow/probation parameter set."""
    model_name: str
    timeframe: str
    param_version: int
    prob_up: float
    confidence: int
    actual_outcome: float = -1.0  # Set when trade resolves (1.0 up, 0.0 down)
    created_at: str = ""

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()


@dataclass
class NurseryEntry:
    """A parameter set under probation."""
    model_name: str
    timeframe: str
    param_version: int
    params: dict                  # The parameter values being tested
    signals: list[ShadowSignal] = field(default_factory=list)
    status: str = "SHADOW"        # SHADOW, PROMOTED, DISCARDED
    parent_version: int = 0
    created_at: str = ""

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()

    @property
    def resolved_signals(self) -> list[ShadowSignal]:
        """Signals that have been resolved (have actual_outcome)."""
        return [s for s in self.signals if s.actual_outcome >= 0.0]

    @property
    def brier_score(self) -> float | None:
        """Compute Brier score over resolved signals."""
        resolved = self.resolved_signals
        if not resolved:
            return None
        return sum(
            (s.prob_up - s.actual_outcome) ** 2 for s in resolved
        ) / len(resolved)

    @property
    def trade_count(self) -> int:
        return len(self.resolved_signals)


class StrategyNursery:
    """Manages shadow/probation testing of new parameter sets."""

    def __init__(self):
        self._entries: list[NurseryEntry] = []

    def admit(
        self,
        model_name: str,
        timeframe: str,
        param_version: int,
        params: dict,
        parent_version: int = 0,
    ) -> NurseryEntry:
        """Admit a new parameter set for shadow testing."""
        entry = NurseryEntry(
            model_name=model_name,
            timeframe=timeframe,
            param_version=param_version,
            params=params,
            parent_version=parent_version,
        )
        self._entries.append(entry)
        logger.info(
            "nursery_admission",
            model=model_name,
            timeframe=timeframe,
            version=param_version,
        )
        return entry

    def record_signal(
        self,
        model_name: str,
        timeframe: str,
        param_version: int,
        prob_up: float,
        confidence: int,
    ) -> None:
        """Record a shadow signal for a nursery entry."""
        entry = self._find_entry(model_name, timeframe, param_version)
        if not entry or entry.status != "SHADOW":
            return

        signal = ShadowSignal(
            model_name=model_name,
            timeframe=timeframe,
            param_version=param_version,
            prob_up=prob_up,
            confidence=confidence,
        )
        entry.signals.append(signal)

    def resolve_signals(
        self,
        model_name: str,
        timeframe: str,
        actual_outcome: float,
    ) -> None:
        """Resolve all unresolved signals for a model/timeframe.

        Called when a market resolves — sets actual_outcome on pending signals.
        """
        for entry in self._entries:
            if (entry.model_name == model_name
                    and entry.timeframe == timeframe
                    and entry.status == "SHADOW"):
                for signal in entry.signals:
                    if signal.actual_outcome < 0.0:
                        signal.actual_outcome = actual_outcome

    def evaluate(
        self,
        model_name: str,
        timeframe: str,
        param_version: int,
        active_brier: float,
    ) -> str:
        """Evaluate a nursery entry against the active model.

        Returns "PROMOTED", "DISCARDED", or "PENDING" (not enough signals yet).
        """
        entry = self._find_entry(model_name, timeframe, param_version)
        if not entry:
            return "PENDING"

        if entry.trade_count < MIN_SHADOW_TRADES:
            return "PENDING"

        shadow_brier = entry.brier_score
        if shadow_brier is None:
            return "PENDING"

        if shadow_brier < active_brier:
            entry.status = "PROMOTED"
            logger.info(
                "nursery_promoted",
                model=model_name,
                version=param_version,
                shadow_brier=round(shadow_brier, 4),
                active_brier=round(active_brier, 4),
            )
            return "PROMOTED"
        else:
            entry.status = "DISCARDED"
            logger.info(
                "nursery_discarded",
                model=model_name,
                version=param_version,
                shadow_brier=round(shadow_brier, 4),
                active_brier=round(active_brier, 4),
            )
            return "DISCARDED"

    def get_shadow_entries(self) -> list[NurseryEntry]:
        """Get all entries still in SHADOW status."""
        return [e for e in self._entries if e.status == "SHADOW"]

    def get_entry(
        self, model_name: str, timeframe: str, param_version: int,
    ) -> NurseryEntry | None:
        return self._find_entry(model_name, timeframe, param_version)

    def _find_entry(
        self, model_name: str, timeframe: str, param_version: int,
    ) -> NurseryEntry | None:
        for entry in self._entries:
            if (entry.model_name == model_name
                    and entry.timeframe == timeframe
                    and entry.param_version == param_version):
                return entry
        return None
